In [1]:
!pip install nptyping beartype

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 991.0 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---- ----------------------------------- 112.6/917.8 kB ? eta -:--:--
   ------- -------------------------------- 174.1/917.8 kB 1.7 MB/s eta 0:00:01
   ---------- ----------------------------- 245.8/917.8 kB 1.9 MB/s eta 0:00:01
   ----------- ---------------------------- 256.0/917.8 kB 1.3 MB/s eta 0:00:01
   --------------------- ------------------ 491.5/917.8 kB 1.9 MB/s eta 0:00:01
   --------------------- ------------------ 501.8/917.8 kB 2.0 MB/s eta 0:00:01
   -------------------------- ------------- 604.2/917.8 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------  911.4/917.8 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 917.8/917.8 kB 2.2 M

## Scalar value

In [2]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object
display(a.dtype) # prints the dtype of the object
display(a.ndim) # prints the number of the object
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object

array(1000)

()

dtype('int32')

0

1

4

## Vector Type

In [6]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(a) # prints
display(a.shape) # prints the shape of the object
display(a.dtype) # prints the dtype of the object
display(a.ndim) # prints the number of the object
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object

array([1, 2, 3, 4])

(4,)

dtype('int32')

1

4

4

## Matrix

In [7]:
import numpy as np

data = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(a) # prints
display(a.shape) # prints the shape of the object
display(a.dtype) # prints the dtype of the object
display(a.ndim) # prints the number of the object
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

(3, 4)

dtype('int32')

2

12

4

## Numpy With NDArray Typing Support

In [26]:
from nptyping import NDArray, UInt64, Shape

data : NDArray[Shape["10"], UInt64] = np.arange(1 ,11)

data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Numpy Advanced Operations vs List Operations

In [30]:
ndata : NDArray[Shape["20"], UInt64] = np.arange (1 ,21)

print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d : (dimension) Functions

In [35]:
from nptyping import Bool

state_bank : NDArray[Shape["10"], UInt64] = np.array([1,7,8,10])
# [1, 7, 8, 10]
# [True, False, False, True]
# variable [True, False, False, True]
select : NDArray[Shape["10"], Bool] = np.array([True, False, False, True])

state_bank[select]

array([ 1, 10])

In [36]:
state_bank : NDArray[Shape["10"], UInt64] = np.array([1,7,8,10])
state_bank % 2 == 0

array([False, False,  True,  True])

In [37]:
state_bank : NDArray[Shape["10"], UInt64] = np.array([1,7,8,10])
state_bank [state_bank % 2 == 0]

array([ 8, 10])

In [33]:
state_bank : NDArray[Shape["10"], UInt64] = np.array([1,7,8,10])

UBL_bank : NDArray[Shape["100"], UInt64] = np.random.randint(1, 100, 20)

print(state_bank)
print(UBL_bank)

[ 1  7  8 10]
[98 77 54  2 62 52 79 33 37 62 67 94 38 38 91 38  4 76 19 18]


In [41]:
display(state_bank)
display(UBL_bank)

np.in1d(state_bank, UBL_bank)

array([ 1,  7,  8, 10])

array([98, 77, 54,  2, 62, 52, 79, 33, 37, 62, 67, 94, 38, 38, 91, 38,  4,
       76, 19, 18])

array([False, False, False, False])

In [40]:
np.intersect1d(state_bank, UBL_bank)

array([], dtype=int32)

# Create Numpy Array

In [46]:
a : NDArray[Shape["Size, Size"], UInt64] = np.array([[1,2,3],[4,5,6]])

print(a)

a : NDArray[Shape["Size, Size"], UInt64] = np.array([[1,2],[4,5]])

print(a)

a : NDArray[Shape["Size, Size"], UInt64] = np.array([["A"],["B"]])

print(a)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [47]:
a : NDArray[Shape["*, *"], UInt64] = np.array([[1,2,3],[4,5,6]])

print(a)

a : NDArray[Shape["*, *"], UInt64] = np.array([[1,2],[4,5]])

print(a)

a : NDArray[Shape["*, *"], UInt64] = np.array([["A"],["B"]])

print(a)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [48]:
np.who()

Name            Shape            Bytes            Type

_               4                4                bool
__              0                0                int32
___             4                4                bool
a               2 x 1            8                str32
data            10               40               int32
_26 (data)      10               40               int32
ndata           20               80               int32
state_bank      4                16               int32
UBL_bank        20               80               int32
select          4                4                bool
_35             2                8                int32
_36             4                4                bool
_37             2                8                int32
_38             0                0                int32
_39 (___)       4                4                bool
_40 (__)        0                0                int32
_41 (_)         4                4                boo

## Create any dimension array

In [55]:
a : NDArray[Shape["Size"], UInt64] = np.arange(1,5)

print(a)

a : NDArray[Shape["Size"], UInt64] = np.arange(1,10)

print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [59]:
a : NDArray[Shape["Size, Size"], UInt64] = np.arange(3*3).reshape(3,3)

print(a)

a : NDArray[Shape["Size"], UInt64] = np.arange(5*3).reshape(5,3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
